import type { Metadata } from "next";
import { Providers } from "./providers";
import localFont from "next/font/local"
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import './globals.css'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <html lang="en">
        <body className="bg-black">
          <Providers>
          {children}
          </Providers>
        </body>
      </html>
  )
}
